feat: query to count of articles by subcategory
Monday-Morning/project-reclamation pull request #132
Opened 2022-05-12 13:33 UTC by 120EE0692

### Solved or Linked Issues

Reference any and all issues solved and related to this pull request here. Mention if there are none.

### Description and Changes

Please describe your pull request with all changes made.

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../README.md) to this repository.

- [ ] Make sure you are requesting to **pull a work/topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **development** (left side). Also you should start _your branch_ off _default branch_ and follow the branch naming guidelines.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation and mentioned the related issues (if appropriate)
- [ ] I have added the appropriate labels, requested a review from a repository manager and assigned myself to this pull request.

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../blob/development/CONTRIBUTING.md) to this repository.

2022-05-13 18:01 UTC, rutajdash requested changes

2022-05-14 04:12 UTC, 120EE0692 commented on server/schema/article/article.datasources.js
> +                  : APIError(null, null, { reason: 'The data being processed was invalid.' }),
Done

2022-05-14 04:12 UTC, 120EE0692 commented on server/schema/article/article.resolver.js
> +
removed

2022-05-14 08:15 UTC, rutajdash approved these changes

2022-05-14 08:15 UTC, merged