chore: fix eslint and prettier issue
Monday-Morning/project-reclamation pull request #165
Opened 2022-12-03 16:34 UTC by 120EE0692

2022-12-03 17:09 UTC, 120EE0692 commented
@rutajdash everything seems fine to me.
<img width="602" alt="image" src="https://user-images.githubusercontent.com/83752052/205453027-09655398-dc61-4222-b91c-2e30fafd0637.png">

2022-12-10 18:46 UTC, rutajdash requested changes

2022-12-10 18:46 UTC, rutajdash commented on server/schema/company/company.datasources.js
>          const _company = ids.map((id) => CompanyModel.findById(id));
You have basically completely made it pointless to use dataloader with how your code runs.

2022-12-10 18:46 UTC, rutajdash commented on server/schema/company/company.datasources.js
>          const _company = ids.map((id) => CompanyModel.findById(id));
Data Loader is supposed to run a single query with all the ids, no run the query within a map this doing a lot of them individually.

2022-12-20 11:19 UTC, rutajdash approved these changes

2022-12-20 11:19 UTC, merged