feat: create squiggle mutation
Monday-Morning/project-reclamation pull request #172
Opened 2023-01-04 04:59 UTC by priyadarshini-silpa

### Solved or Linked Issues

Reference any and all issues solved and related to this pull request here. Mention if there are none.

### Description and Changes

Please describe your pull request with all changes made.

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../README.md) to this repository.

- [ ] Make sure you are requesting to **pull a work/topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **development** (left side). Also you should start _your branch_ off _default branch_ and follow the branch naming guidelines.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation and mentioned the related issues (if appropriate)
- [ ] I have added the appropriate labels, requested a review from a repository manager and assigned myself to this pull request.

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../blob/development/CONTRIBUTING.md) to this repository.

2023-01-09 17:04 UTC, 120EE0692 reviewed
@rutajdash code seems fine to me, permission check to be added.

2023-01-09 20:51 UTC, rutajdash requested changes

2023-01-09 20:51 UTC, rutajdash commented on server/schema/squiggle/squiggle.datasources.js
> +};
Please add an empty line here for code cleanliness.

2023-01-09 20:51 UTC, rutajdash commented on server/schema/squiggle/squiggle.resolver.js
> +
Please add the required permission checks for this mutation to be called.

2023-01-31 13:59 UTC, rutajdash approved these changes

2023-02-04 06:02 UTC, 120EE0692 approved these changes

2023-02-06 15:11 UTC, merged